config/routes.rb
Rails.application.routes.draw do

  resources :albums
  resources :smartphones
  resources :reviews
  resources :comments
  resources :users
  resources :products
  get 'home/index'
  get 'register' => 'users#new'
  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  delete 'logout' => 'logins#destroy'
  get 'home' => 'home#index'
  get 'index' => 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/smartphone.rb
class Smartphone < ApplicationRecord
end

app/controllers/smartphones_controller.rb
class SmartphonesController < ApplicationController
  before_action :set_smartphone, only: [:show, :edit, :update, :destroy]

  # GET /smartphones
  # GET /smartphones.json
  def index
    @smartphones = Smartphone.all
  end

  # GET /smartphones/1
  # GET /smartphones/1.json
  def show
  end

  # GET /smartphones/new
  def new
    @smartphone = Smartphone.new
  end

  # GET /smartphones/1/edit
  def edit
  end

  # POST /smartphones
  # POST /smartphones.json
  def create
    @smartphone = Smartphone.new(smartphone_params)

    respond_to do |format|
      if @smartphone.save
        format.html { redirect_to @smartphone, notice: 'Smartphone was successfully created.' }
        format.json { render :show, status: :created, location: @smartphone }
      else
        format.html { render :new }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /smartphones/1
  # PATCH/PUT /smartphones/1.json
  def update
    respond_to do |format|
      if @smartphone.update(smartphone_params)
        format.html { redirect_to @smartphone, notice: 'Smartphone was successfully updated.' }
        format.json { render :show, status: :ok, location: @smartphone }
      else
        format.html { render :edit }
        format.json { render json: @smartphone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /smartphones/1
  # DELETE /smartphones/1.json
  def destroy
    @smartphone.destroy
    respond_to do |format|
      format.html { redirect_to smartphones_url, notice: 'Smartphone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_smartphone
      @smartphone = Smartphone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def smartphone_params
      params.require(:smartphone).permit(:name, :category, :picture, :rate_AVG)
    end
end

app/helpers/smartphones_helper.rb
module SmartphonesHelper
end

app/views/smartphones/_form.html.erb
<%= form_with(model: smartphone, local: true) do |form| %>
  <% if smartphone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(smartphone.errors.count, "error") %> prohibited this smartphone from being saved:</h2>

      <ul>
      <% smartphone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :smartphone_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :smartphone_category %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :smartphone_picture %>
  </div>

  <div class="field">
    <%= form.label :rate_AVG %>
    <%= form.text_field :rate_AVG, id: :smartphone_rate_AVG %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/smartphones/edit.html.erb
<h1>Editing Smartphone</h1>

<%= render 'form', smartphone: @smartphone %>

<%= link_to 'Show', @smartphone %> |
<%= link_to 'Back', smartphones_path %>

app/views/smartphones/index.html.erb
<% content_for :body do %>
<div class="container" style="margin-top: 336px;">
  <p id="notice"><%= notice %></p>

  <h1>Smartphones</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Picture</th>
        <th>Rate avg</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @smartphones.each do |smartphone| %>
      <tr>
        <td><%= smartphone.name %></td>
        <td><%= smartphone.category %></td>
        <td><%= smartphone.picture %></td>
        <td><%= smartphone.rate_AVG %></td>
        <td><%= link_to 'Show', smartphone %></td>
        <td><%= link_to 'Edit', edit_smartphone_path(smartphone) %></td>
        <td><%= link_to 'Destroy', smartphone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Smartphone', new_smartphone_path %>
</div>
<% end %>

app/views/smartphones/new.html.erb
<% content_for :body do %>
<div style="margin-top: 75px;">
	<h1>New Smartphone</h1>

	<%= render 'form', smartphone: @smartphone %>

	<%= link_to 'Back', smartphones_path %>
</div>
<% end %>

app/views/smartphones/show.html.erb
<% content_for :body do %>
<div class="container" style="margin-top: 336px;">
<p id="notice"><%= notice %></p>

<p>
	<strong>Name:</strong>
	<%= @smartphone.name %>
</p>

<p>
	<strong>Category:</strong>
	<%= @smartphone.category %>
</p>

<p>
	<strong>Picture:</strong>
	<%= @smartphone.picture %>
</p>

<p>
	<strong>Rate avg:</strong>
	<%= @smartphone.rate_AVG %>
</p>

<%= link_to 'Edit', edit_smartphone_path(@smartphone) %> |
<%= link_to 'Back', smartphones_path %>
</div>
<% end %>