config/routes.rb
Rails.application.routes.draw do

  resources :albums
  resources :smartphones
  resources :reviews
  resources :comments
  resources :users
  resources :products
  get 'home/index'
  get 'register' => 'users#new'
  get 'login' => 'logins#new'
  post 'login' => 'logins#create'
  delete 'logout' => 'logins#destroy'
  get 'home' => 'home#index'
  get 'index' => 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  belongs_to :smartphone
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :smartphone
end

app/models/smartphone.rb
class Smartphone < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :name, :email ,:password ,:presence => true 
	validates :name, :uniqueness => true
	validates :email, :uniqueness => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :picture, :user_id, :smartphone_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user=session[:user]
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	skip_before_action :require_login , only: [:new, :create]
  def new
  end
  def create 
    user = User.find_by name: params[:session][:name].downcase
    if user && user.authenticate(params[:session][:password])
    	flash[:success]="login success"
    	log_in user
    	redirect_to user
      #TODO save user infor into session
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end
  def destroy
  	log_out
  	flash[:success]="you are logged out"
  	redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login , only: [:new,:show, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by id: params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'register success.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
    
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :email,:password,:password_confirmation)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
	def log_in 	user 
		session[:user_id]=user.id
	end
	def log_out 
		session.delete :user_id
	end
	def current_user
		@current_user ||= User.find_by id: session[:user_id]
	end
	def logged_in?
		current_user.present? 
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/smartphones_helper.rb
module SmartphonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer text-center spacer">
    <p class="wowload flipInX animated" style="visibility: visible; animation-name: flipInX;"><a href="#"><i class="fa fa-facebook fa-2x"></i></a> <a href="#"><i class="fa fa-instagram fa-2x"></i></a> <a href="#"><i class="fa fa-twitter fa-2x"></i></a> <a href="#"><i class="fa fa-flickr fa-2x"></i></a> </p>
    Powered by: <a href="https://thebootstrapthemes.com/live/thebootstrapthemes-photography/thebootstrapthemes.com">Cutyremon</a>
  </div>
  <!-- # Footer Ends -->
  <a href="#home" class="gototop "><i class="fa fa-angle-up  fa-3x"></i></a>





  <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
  <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title">Title</h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->    
  </div>

</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar-wrapper">
		<div class="container">

			<div class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="top-nav">
				<div class="container">
					<div class="navbar-header">
						<!-- Logo Starts -->
						<h2 style="font-size: 34px;">Smartphone</h2>
						<!-- #Logo Ends -->


						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>

					</div>


					<!-- Nav Starts -->
					<div>
						<ul class="nav navbar-nav navbar-right">
							<li class="active"><%= link_to "home", home_path %></li>
							<li>
								<%= link_to "Smartphone", smartphones_path %>
							</li>
							<li>
								<%= link_to "Review", reviews_path %>
							</li>
							<li><%= link_to "Album", albums_path %>
							</li>
							<li><a href="#contact">Contact</a></li>
							<% if(current_user) %>
							<li><%= link_to current_user.name, user_path(current_user) %></li>
							<% else %>
							<li>
								<%= link_to "Login", login_path %>
								
							</li>
							<% end %>
						</ul>
					</div>
					<!-- #Nav Ends -->

				</div>
			</div>

		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <!-- favicon -->
  <link rel="shortcut icon" href="https://thebootstrapthemes.com/live/thebootstrapthemes-photography/images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="https://thebootstrapthemes.com/live/thebootstrapthemes-photography/images/favicon.ico" type="image/x-icon">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Cutyremon/<%= yield(:title) %></title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= render 'layouts/shim' %>

</head>

<body>
	<%= render 'layouts/header' %>
		<%= yield(:body) %>
	<%= render 'layouts/footer' %>
</body>
</html>